### ISSUE TITLE
Test failures with `psutil==6.0.0`

### ISSUE THREAD

**Issue by mgorny** [saltstack/pytest-shell-utilities#44] opened 2024-07-11 18:35 UTC
After upgrading `psutil` to the new version 6.0.0, the tests are failing:

<details>

```pytb
$ pip install -e . pytest-subtests
[…]
$ python -m pytest
========================================================= test session starts =========================================================
platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
rootdir: /tmp/pytest-shell-utilities
configfile: pytest.ini
testpaths: tests/
plugins: subtests-0.13.0, skip-markers-1.5.1, helpers-namespace-2021.12.29, shell-utilities-1.9.1.dev1+g3b68751
collected 82 items                                                                                                                    

tests/functional/shell/test_daemon.py .sFF.EFFF...FFF                                                                           [ 17%]
tests/functional/shell/test_fixture.py ...                                                                                      [ 20%]
tests/functional/shell/test_script_subprocess.py .................,,,.                                                          [ 42%]
tests/functional/shell/test_subprocess.py ...................                                                                   [ 65%]
tests/functional/test_exceptions.py ........                                                                                    [ 75%]
tests/unit/customtypes/test_callback.py .....                                                                                   [ 81%]
tests/unit/utils/processes/test_processresult.py ....,,,,.,,,,.                                                                 [ 89%]
tests/unit/utils/processes/test_processresult_matcher.py ..                                                                     [ 91%]
tests/unit/utils/test_format_callback_to_string.py .....                                                                        [ 97%]
tests/unit/utils/test_ports.py .                                                                                                [ 98%]
tests/unit/utils/test_time.py .                                                                                                 [100%]

=============================================================== ERRORS ================================================================
_____________________________ ERROR at teardown of test_stopped_context_manager_raises_FactoryNotRunning ______________________________

self = Daemon(cwd=PosixPath('/tmp/pytest-shell-utilities'), slow_stop=True, timeout=None, script_name='/tmp/pytest-shell-util...thon', base_script_args=['/tmp/tmp8lrvhad_.py'], check_ports=[12345], extra_cli_arguments_after_first_start_failure=[])

    def terminate(self) -> ProcessResult:
        """
        Terminate the started subprocess.
        """
>       return self.impl.terminate()

src/pytestshellutils/shell.py:461: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/pytestshellutils/shell.py:875: in terminate
    callback()
src/pytestshellutils/customtypes.py:86: in __call__
    return self.func(*_args, **_kwargs)
src/pytestshellutils/shell.py:1281: in _terminate_processes_matching_listen_ports
    for process in psutil.process_iter(["connections"]):
.venv/lib/python3.12/site-packages/psutil/__init__.py:1516: in process_iter
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = psutil.Process(pid=1, name='systemd', status='sleeping', started='16:33:43'), attrs = {'connections'}, ad_value = None

    def as_dict(self, attrs=None, ad_value=None):
        """Utility method returning process information as a
        hashable dictionary.
        If *attrs* is specified it must be a list of strings
        reflecting available Process class' attribute names
        (e.g. ['cpu_times', 'name']) else all public (read
        only) attributes are assumed.
        *ad_value* is the value which gets assigned in case
        AccessDenied or ZombieProcess exception is raised when
        retrieving that particular process information.
        """
        valid_names = _as_dict_attrnames
        if attrs is not None:
            if not isinstance(attrs, (list, tuple, set, frozenset)):
                msg = "invalid attrs type %s" % type(attrs)
                raise TypeError(msg)
            attrs = set(attrs)
            invalid_names = attrs - valid_names
            if invalid_names:
                msg = "invalid attr name%s %s" % (
                    "s" if len(invalid_names) > 1 else "",
                    ", ".join(map(repr, invalid_names)),
                )
>               raise ValueError(msg)
E               ValueError: invalid attr name 'connections'

.venv/lib/python3.12/site-packages/psutil/__init__.py:547: ValueError
--------------------------------------------------------- Captured log setup ----------------------------------------------------------
DEBUG    tests.conftest:conftest.py:78 Created python file with contents:
>>>>> /tmp/tmp8lrvhad_.py >>>>>
# coding=utf-8

import os
import sys
import time
import socket
import multiprocessing

def main():

    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind(('127.0.0.1', 12345))
    sock.listen(5)
    try:
        while True:
            connection, address = sock.accept()
            connection.close()
    except (KeyboardInterrupt, SystemExit):
        pass
    finally:
        sock.close()
    sys.exit(0)

# Support for windows test runs
if __name__ == '__main__':
    multiprocessing.freeze_support()
    main()
<<<<< /tmp/tmp8lrvhad_.py <<<<<
-------------------------------------------------------- Captured log teardown --------------------------------------------------------
DEBUG    pytestshellutils.customtypes:customtypes.py:85 Running Daemon._terminate_processes_matching_listen_ports()
============================================================== FAILURES ===============================================================
__________________________________________________ test_started_context_manager[0.1] __________________________________________________

request = <FixtureRequest for <Function test_started_context_manager[0.1]>>
tempfiles = <tests.conftest.Tempfiles object at 0x7f584e4ce4e0>, start_timeout = 0.1

    @pytest.mark.parametrize("start_timeout", [0.1, 0.3])
    def test_started_context_manager(
        request: FixtureRequest, tempfiles: Tempfiles, start_timeout: float
    ) -> None:
        script = tempfiles.makepyfile(
            r"""
            # coding=utf-8
    
            import sys
            import time
            import multiprocessing
    
            def main():
                time.sleep(3)
                sys.stdout.write("Done!\n")
                sys.stdout.flush()
                sys.exit(0)
    
            # Support for windows test runs
            if __name__ == '__main__':
                multiprocessing.freeze_support()
                main()
            """,
            executable=True,
        )
        daemon = Daemon(
            script_name=sys.executable,
            base_script_args=[script],
            start_timeout=2,
            max_start_attempts=1,
            check_ports=[12345],
        )
        # Make sure the daemon is terminated no matter what
        request.addfinalizer(daemon.terminate)
        with pytest.raises(FactoryNotStarted) as exc:
>           daemon.start(start_timeout=start_timeout)

tests/functional/shell/test_daemon.py:273: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src/pytestshellutils/shell.py:1076: in start
    return self.impl.start(
src/pytestshellutils/shell.py:829: in start
    self.terminate()
src/pytestshellutils/shell.py:875: in terminate
    callback()
src/pytestshellutils/customtypes.py:86: in __call__
    return self.func(*_args, **_kwargs)
src/pytestshellutils/shell.py:1281: in _terminate_processes_matching_listen_ports
    for process in psutil.process_iter(["connections"]):
.venv/lib/python3.12/site-packages/psutil/__init__.py:1516: in process_iter
    proc.info = proc.as_dict(attrs=attrs, ad_value=ad_value)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = psutil.Process(pid=1, name='systemd', status='sleeping', started='16:33:43'), attrs = {'connections'}, ad_value = None

    def as_dict(self, attrs=None, ad_value=None):
        """Utility method returning process information as a
        hashable dictionary.
        If *attrs* is specified it must be a list of strings
        reflecting available Process class' attribute names
        (e.g. ['cpu_times', 'name']) else all public (read
        only) attributes are assumed.
        *ad_value* is the value which gets assigned in case
        AccessDenied or ZombieProcess exception is raised when
        retrieving that particular process information.
        """
        valid_names = _as_dict_attrnames
        if attrs is not None:
            if not isinstance(attrs, (list, tuple, set, frozenset)):
                msg = "invalid attrs type %s" % type(attrs)
                raise TypeError(msg)
            attrs = set(attrs)
            invalid_names = attrs - valid_names
            if invalid_names:
                msg = "invalid attr name%s %s" % (
                    "s" if len(invalid_names) > 1 else "",
                    ", ".join(map(repr, invalid_names)),
                )
>               raise ValueError(msg)
E               ValueError: invalid attr name 'connections'

.venv/lib/python3.12/site-packages/psutil/__init__.py:547: ValueError
---------------------------------------------------------- Captured log call ----------------------------------------------------------
DEBUG    tests.conftest:conftest.py:78 Created python file with contents:
>>>>> /tmp/tmpr0_g18ti.py >>>>>
# coding=utf-8

import sys
import time
import multiprocessing

def main():
    time.sleep(3)
    sys.stdout.write("Done!\n")
    sys.stdout.flush()
    sys.exit(0)

# Support for windows test runs
if __name__ == '__main__':
    multiprocessing.freeze_support()
    main()
<<<<< /tmp/tmpr0_g18ti.py <<<<<

INFO     pytestshellutils.shell:shell.py:779 Starting Daemon(cwd=PosixPath('/tmp/pytest-shell-utilities'), slow_stop=True, timeout=None, script_name='/tmp/pytest-shell-utilities/.venv/bin/python', base_script_args=['/tmp/tmpr0_g18ti.py'], check_ports=[12345], extra_cli_arguments_after_first_start_failure=[]). Attempt: 1 of 1
INFO     pytestshellutils.shell:shell.py:338 Daemon(cwd=PosixPath('/tmp/pytest-shell-utilities'), slow_stop=True, timeout=None, script_name='/tmp/pytest-shell-utilities/.venv/bin/python', base_script_args=['/tmp/tmpr0_g18ti.py'], check_ports=[12345], extra_cli_arguments_after_first_start_failure=[]) is running ['/tmp/pytest-shell-utilities/.venv/bin/python', '/tmp/tmpr0_g18ti.py'] in CWD: /tmp/pytest-shell-utilities ...
DEBUG    pytestshellutils.shell:shell.py:1202 Daemon(cwd=PosixPath('/tmp/pytest-shell-utilities'), slow_stop=True, timeout=None, script_name='/tmp/pytest-shell-utilities/.venv/bin/python', base_script_args=['/tmp/tmpr0_g18ti.py'], check_ports=[12345], extra_cli_arguments_after_first_start_failure=[]) is running start checks
DEBUG    pytestshellutils.customtypes:customtypes.py:85 Running Daemon._check_listening_ports(1720722743.8886774)
DEBUG    pytestshellutils.shell:shell.py:1244 Listening ports to check for Daemon(cwd=PosixPath('/tmp/pytest-shell-utilities'), slow_stop=True, timeout=None, script_name='/tmp/pytest-shell-utilities/.venv/bin/python', base_script_args=['/tmp/tmpr0_g18ti.py'], check_ports=[12345], extra_cli_arguments_after_first_start_failure=[]): {12345}
ERROR    pytestshellutils.shell:shell.py:1255 Failed to check ports after 1.50 seconds for Daemon(cwd=PosixPath('/tmp/pytest-shell-utilities'), slow_stop=True, timeout=None, script_name='/tmp/pytest-shell-utilities/.venv/bin/python', base_script_args=['/tmp/tmpr0_g18ti.py'], check_ports=[12345], extra_cli_arguments_after_first_start_failure=[]). Remaining ports to check: {12345}
ERROR    pytestshellutils.shell:shell.py:1221 Failed to run start check callbacks after 1.50 seconds for Daemon(cwd=PosixPath('/tmp/pytest-shell-utilities'), slow_stop=True, timeout=None, script_name='/tmp/pytest-shell-utilities/.venv/bin/python', base_script_args=['/tmp/tmpr0_g18ti.py'], check_ports=[12345], extra_cli_arguments_after_first_start_failure=[]). Remaining start check callbacks: [Callback(func=<bound method Daemon._check_listening_ports of Daemon(cwd=PosixPath('/tmp/pytest-shell-utilities'), slow_stop=True, timeout=None, script_name='/tmp/pytest-shell-utilities/.venv/bin/python', base_script_args=['/tmp/tmpr0_g18ti.py'], check_ports=[12345], extra_cli_arguments_after_first_start_failure=[])>, args=(), kwargs={})]
INFO     pytestshellutils.shell:shell.py:222 Stopping Daemon(cwd=PosixPath('/tmp/pytest-shell-utilities'), slow_stop=True, timeout=None, script_name='/tmp/pytest-shell-utilities/.venv/bin/python', base_script_args=['/tmp/tmpr0_g18ti.py'], check_ports=[12345], extra_cli_arguments_after_first_start_failure=[])
INFO     pytestshellutils.shell:shell.py:292 Daemon ProcessResult
 Command Line: ['/tmp/pytest-shell-utilities/.venv/bin/python', '/tmp/tmpr0_g18ti.py']
 Returncode: -15

DEBUG    pytestshellutils.customtypes:customtypes.py:85 Running Daemon._terminate_processes_matching_listen_ports()
[...]
======================================================= short test summary info =======================================================
FAILED tests/functional/shell/test_daemon.py::test_started_context_manager[0.1] - ValueError: invalid attr name 'connections'
FAILED tests/functional/shell/test_daemon.py::test_started_context_manager[0.3] - ValueError: invalid attr name 'connections'
FAILED tests/functional/shell/test_daemon.py::test_stopped_context_manager - ValueError: invalid attr name 'connections'
FAILED tests/functional/shell/test_daemon.py::test_daemon_callbacks - ValueError: invalid attr name 'connections'
FAILED tests/functional/shell/test_daemon.py::test_daemon_start_check_callbacks - ValueError: invalid attr name 'connections'
FAILED tests/functional/shell/test_daemon.py::test_exact_max_start_attempts[1] - ValueError: invalid attr name 'connections'
FAILED tests/functional/shell/test_daemon.py::test_exact_max_start_attempts[2] - ValueError: invalid attr name 'connections'
FAILED tests/functional/shell/test_daemon.py::test_exact_max_start_attempts[3] - ValueError: invalid attr name 'connections'
ERROR tests/functional/shell/test_daemon.py::test_stopped_context_manager_raises_FactoryNotRunning - ValueError: invalid attr name 'connections'
================================ 8 failed, 73 passed, 1 skipped, 1 error, 11 subtests passed in 24.36s ================================
```
</details>

(I had to cut the log because of it was too big for GitHub)

Reproduced on top of 3b68751cba3c05c2889b11cb210d1ade1a83eab4. Downgrading to `psutil<6` makes the tests pass.

**Comment by lkubb** [comment] 2024-07-24 13:43
Caused by: https://github.com/giampaolo/psutil/commit/20ed8f9b3d53847408e08442857704590d4f8b4c

It should be changed to `net_connections` if psutil >= 6 is in use

**Comment by dmurphy18** [comment] 2024-08-14 21:28
@mgorny Can you provide details of the system you generated this on, tried to repeat it on Rocky Linux 9 without luck
```
[root@dhcp-10-47-15-216 dev]# pip3 list | grep psutil
psutil              6.0.0
[root@dhcp-10-47-15-216 dev]# pip3 list | grep pytest
pytest              8.3.2
pytest-subtests     0.13.1
[root@dhcp-10-47-15-216 dev]# python3 -m pytest
========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.9.18, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/david/dev
plugins: subtests-0.13.1
collected 0 items                                                                                                                                                                                        

========================================================================================= no tests ran in 0.02s ==========================================================================================
[root@dhcp-10-47-15-216 dev]# python3 --version
Python 3.9.18
[root@dhcp-10-47-15-216 dev]#```

Or any other steps to reproduce the issue, as with any change will need to generate a test to exercise the code changes
Will try with Debian 12 while waiting response

**Comment by mgorny** [comment] 2024-08-15 02:53
You need to run it inside `pytest-shell-utilities` git checkout, or otherwise provide path to tests.

**Comment by dmurphy18** [comment] 2024-08-26 22:13
Closing this since release of pytest-shell-=utilities v1.9.3 has support for psutil v6.0.0

**Closed as completed by dmurphy18** 2024-08-26 22:13 UTC
Labels: bug

**Comment by mgorny** [comment] 2024-08-27 06:10
Thanks!
